language: node_js
node_js:
  - "10.15.3"
script:
  - "npm run -s cover"
after_script:
  - "./node_modules/.bin/remap-istanbul -i coverage/coverage-final.json -t lcovonly | ./node_modules/.bin/coveralls"
